export const ADD_TODO = 'TODO/ADD'
export const TOGGLE_TODO = 'TODO/TOGGLE'
export const REMOVE_TODO = 'TODO/REMOVE'
export const GET_TODO = 'TODO/GET'
export const LOAD_TODO = 'TODO/LOAD'
export const SUCCESS_TODO = 'TODO/SUCCESS'
export const FAIL_TODO = 'TODO/FAIL'
