export const ADD_TODO = 'TODO/ADD'
export const TOGGLE_TODO = 'TODO/TOGGLE'
export const REMOVE_TODO = 'TODO/REMOVE'
export const LOAD_TODO = 'TODO/LOAD'
export const GET_TODO_SUCCESS = 'TODO/GET_SUCCESS'
export const FAIL_TODO = 'TODO/FAIL'
